<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kępa
*/
class BannerRecord extends TActiveRecord
{
	const TABLE='Banner';

	public $ID;
	public $Name;
	public $Description;
	public $Url;
	public $IsBanner;

	/**
	* @param string $className
	* @return BannerRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
