<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kępa
*/
class CatalogueRecord extends TActiveRecord
{
	const TABLE='catalogue';

	public $cat_id;
	public $name;
	public $source_lang;
	public $target_lang;
	public $date_created;
	public $date_modified;
	public $author;
	public $MasterName;
	public $ShortName;
	public $Photo;
	
	/**
	* @param string $className
	* @return CatalogueRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
