<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kępa
*/
class FilesRecord extends TActiveRecord
{
	const TABLE='Files';

	public $ID;
	public $Name;
	public $GalleryID;
	public $PagesID;
	public $Position;
	public $IsParent;
	public $Description;
	public $Url;
	
	/**
	* @param string $className
	* @return FilesRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
} 
?>
