<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kêpa
*/
class nLayoutRecord extends TActiveRecord
{
	const TABLE='nLayout';

	public $ID;
	public $PlaneText;
	public $HtmlText;
	public $nNewsletterID;

	/**
	* @param string $className
	* @return nLayoutRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
