<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kêpa
*/
class nNewsletterRecord extends TActiveRecord
{
	const TABLE='nNewsletter';

	public $ID;
	public $Name;
	public $Status;

	/**
	* @param string $className
	* @return nNewsletterRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
