<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kêpa
*/
class nSenderRecord extends TActiveRecord
{
	const TABLE='nSender';

	public $ID;
	public $Email;
	public $Status;
	public $AddDate;
	public $nLayoutID;

	/**
	* @param string $className
	* @return nSenderRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
