<?php
/**
* Generated by Venom Project
*
* mail: biuro@venomproject.com
* mobile: 510-321-811
* www: http://www.venomproject.com
* 
* Autor : Karol Kępa
*/
class UserRecord extends TActiveRecord
{
	const TABLE='User';

	public $Username;
	public $Email;
	public $Password;
	public $Soul;
	public $Role;
	public $PagesID;
	public $ID;
	public $Name;
	/**
	* @param string $className
	* @return UserRecord
	*/
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
